plugins:
    psutil:
        executor: host_agent
        source: https://github.com/cloudify-cosmo/cloudify-psutil-plugin/archive/master.zip
        package_name: cloudify-psutil-plugin
        package_version: '1.0'
